blank_issues_enabled: true
contact_links:
  - name: ğŸ‘‹ Slack
    url: https://redpanda.com/slack
    about: Chat about all things Funes. Join the conversation!
  - name: â“ Github Discussions
    url: https://github.com/funes-data/funes/discussions
    about: Longer, more involved discussions
  - name: ğŸ’­ Product Feedback
    url: https://redpanda.com/feedback
    about: Let us know how we can improve your experience


